sources:
  rss: ["https://example.com/feed1.xml", "https://example.com/feed2.xml"]
  json: []
duckdb_path: "./data/events.db"
sqlite_path: "./data/articles.db"
vault_path: "./vault"
geojson_output: "./data/geojson/events.geojson"
csv_output: "./data/events.csv"
